import argparse
import csv
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from dotenv import load_dotenv
from sqlalchemy import create_engine, text

from src.config import BASE_DIR

load_dotenv()

CSV_PATH = os.path.join(BASE_DIR, "data", "nutrients_csvfile.csv")


def clean_val(val):
    """Cleans numeric values from CSV (handles 't', 'a', commas)."""
    if not val:
        return 0.0
    val = val.strip().lower()
    if val in ['t', 'a']:
        return 0.0
    val = val.replace(',', '')
    try:
        return float(val)
    except ValueError:
        return 0.0


def parse_csv() -> list[dict]:
    """Parse CSV and normalize all values to per-100g. Pure data, no DB dependency."""
    items = []
    with open(CSV_PATH, mode='r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            name = row.get("Food")
            grams_str = row.get("Grams")

            if not name or not grams_str:
                continue

            grams = clean_val(grams_str)
            if grams == 0:
                print(f"Skipping {name} due to 0 grams.")
                continue

            calories = clean_val(row.get("Calories"))
            protein = clean_val(row.get("Protein"))
            fat = clean_val(row.get("Fat"))
            carbs = clean_val(row.get("Carbs"))
            category = row.get("Category")

            if category and "Breads" in category:
                name = f"{category} - {name}"

            items.append({
                "name": name,
                "calories": round((calories / grams) * 100, 2),
                "protein": round((protein / grams) * 100, 2),
                "fat": round((fat / grams) * 100, 2),
                "carbs": round((carbs / grams) * 100, 2),
            })
    return items


def ingest_sqlite(items: list[dict]):
    """Insert via ORM — existing path for local SQLite dev."""
    from src.database import get_db_session
    from src.models import FoodItem

    session = get_db_session()
    session.execute(text("DELETE FROM daily_logs"))
    session.execute(text("DELETE FROM food_items"))
    session.commit()

    food_items = [FoodItem(**item) for item in items]
    session.add_all(food_items)
    session.commit()
    session.close()


def ingest_postgres(items: list[dict]):
    """Insert via raw SQL — bypasses ORM model (which still has integer PKs).

    Postgres tables use UUID PKs (auto-generated by gen_random_uuid()),
    so we insert without specifying id.
    """
    db_url = os.getenv("SUPABASE_DB_URL")
    if not db_url:
        raise ValueError("SUPABASE_DB_URL not set in environment. Add it to .env")

    engine = create_engine(db_url)
    with engine.connect() as conn:
        conn.execute(text("DELETE FROM daily_logs"))
        conn.execute(text("DELETE FROM food_items"))
        conn.commit()

        conn.execute(
            text("""
                INSERT INTO food_items (name, calories, protein, fat, carbs, source)
                VALUES (:name, :calories, :protein, :fat, :carbs, 'database')
            """),
            items,
        )
        conn.commit()
    engine.dispose()


def main():
    parser = argparse.ArgumentParser(description="Ingest nutrition CSV into database")
    parser.add_argument(
        "--target",
        choices=["sqlite", "supabase"],
        default="sqlite",
        help="Target database (default: sqlite)",
    )
    args = parser.parse_args()

    items = parse_csv()
    print(f"Parsed {len(items)} food items from CSV")

    if args.target == "sqlite":
        ingest_sqlite(items)
    else:
        ingest_postgres(items)

    print(f"Ingestion complete! Target: {args.target}, items: {len(items)}")


if __name__ == "__main__":
    main()
