"""add source column to food_items

Revision ID: 4652804c7c7f
Revises: cfec3ad93406
Create Date: 2026-03-07 13:00:13.627562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4652804c7c7f'
down_revision: Union[str, None] = 'cfec3ad93406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), server_default='database', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
